spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products-service/**
          filters:
            - RewritePath=/products-service/(?<path>.*), /$\{path}
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/orders-service/**
          filters:
            - RewritePath=/orders-service/(?<path>.*), /$\{path}